/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as ImageRouteImport } from './routes/image'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/image': typeof ImageRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/pages': typeof PagesRoute
  '/pdf': typeof PdfRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/image': typeof ImageRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/pages': typeof PagesRoute
  '/pdf': typeof PdfRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/image': typeof ImageRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/pages': typeof PagesRoute
  '/pdf': typeof PdfRoute
  '/video': typeof VideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/image'
    | '/merge'
    | '/metadata'
    | '/pages'
    | '/pdf'
    | '/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/image'
    | '/merge'
    | '/metadata'
    | '/pages'
    | '/pdf'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/image'
    | '/merge'
    | '/metadata'
    | '/pages'
    | '/pdf'
    | '/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImageRoute: typeof ImageRoute
  MergeRoute: typeof MergeRoute
  MetadataRoute: typeof MetadataRoute
  PagesRoute: typeof PagesRoute
  PdfRoute: typeof PdfRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImageRoute: ImageRoute,
  MergeRoute: MergeRoute,
  MetadataRoute: MetadataRoute,
  PagesRoute: PagesRoute,
  PdfRoute: PdfRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
