/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as ImageRouteImport } from './routes/image'
import { Route as Feature4RouteImport } from './routes/feature4'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogIntroducingStickyRouteImport } from './routes/blog.introducing-sticky'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const Feature4Route = Feature4RouteImport.update({
  id: '/feature4',
  path: '/feature4',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIntroducingStickyRoute = BlogIntroducingStickyRouteImport.update({
  id: '/blog/introducing-sticky',
  path: '/blog/introducing-sticky',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feature4': typeof Feature4Route
  '/image': typeof ImageRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/pdf': typeof PdfRoute
  '/video': typeof VideoRoute
  '/blog/introducing-sticky': typeof BlogIntroducingStickyRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feature4': typeof Feature4Route
  '/image': typeof ImageRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/pdf': typeof PdfRoute
  '/video': typeof VideoRoute
  '/blog/introducing-sticky': typeof BlogIntroducingStickyRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feature4': typeof Feature4Route
  '/image': typeof ImageRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/pdf': typeof PdfRoute
  '/video': typeof VideoRoute
  '/blog/introducing-sticky': typeof BlogIntroducingStickyRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/feature4'
    | '/image'
    | '/merge'
    | '/metadata'
    | '/pdf'
    | '/video'
    | '/blog/introducing-sticky'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/feature4'
    | '/image'
    | '/merge'
    | '/metadata'
    | '/pdf'
    | '/video'
    | '/blog/introducing-sticky'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/feature4'
    | '/image'
    | '/merge'
    | '/metadata'
    | '/pdf'
    | '/video'
    | '/blog/introducing-sticky'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Feature4Route: typeof Feature4Route
  ImageRoute: typeof ImageRoute
  MergeRoute: typeof MergeRoute
  MetadataRoute: typeof MetadataRoute
  PdfRoute: typeof PdfRoute
  VideoRoute: typeof VideoRoute
  BlogIntroducingStickyRoute: typeof BlogIntroducingStickyRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature4': {
      id: '/feature4'
      path: '/feature4'
      fullPath: '/feature4'
      preLoaderRoute: typeof Feature4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/introducing-sticky': {
      id: '/blog/introducing-sticky'
      path: '/blog/introducing-sticky'
      fullPath: '/blog/introducing-sticky'
      preLoaderRoute: typeof BlogIntroducingStickyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Feature4Route: Feature4Route,
  ImageRoute: ImageRoute,
  MergeRoute: MergeRoute,
  MetadataRoute: MetadataRoute,
  PdfRoute: PdfRoute,
  VideoRoute: VideoRoute,
  BlogIntroducingStickyRoute: BlogIntroducingStickyRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
